from __future__ import annotations

import asyncio
import io
import json
import logging
import re
import zipfile
from pathlib import Path
from typing import Any, Awaitable, Optional
from urllib.parse import unquote, urlparse
from urllib.request import url2pathname

import httpx

from apps.api.models.schemas import BrandAssets, Persona

from . import _storage as storage

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_") or "brand"


async def _fetch(client: httpx.AsyncClient, url: Optional[str]) -> Optional[bytes]:
    """Fetch bytes from http(s) or file:// URLs. Returns None on failure."""
    if not url:
        return None
    parsed = urlparse(url)
    try:
        if parsed.scheme in ("http", "https"):
            resp = await client.get(url, timeout=15.0, follow_redirects=True)
            resp.raise_for_status()
            return resp.content
        if parsed.scheme == "file":
            local_path = url2pathname(unquote(parsed.path))
            return Path(local_path).read_bytes()
        logger.warning("unsupported URL scheme: %s", parsed.scheme)
        return None
    except Exception as exc:
        logger.warning("fetch failed for %s: %s", url, exc)
        return None


def _brand_data_dump(brand: BrandAssets, persona: Persona) -> bytes:
    """Structured brand data — palette, typography, voice. No image URLs."""
    payload = {
        "brand_name": brand.brand_name,
        "tagline": brand.tagline,
        "palette": [{"hex": c.hex, "role": c.role, "name": c.name} for c in brand.palette],
        "typography": (
            {
                "display": {
                    "family": brand.typography.display.family,
                    "weights": brand.typography.display.weights,
                    "google_url": brand.typography.display.google_url,
                },
                "body": {
                    "family": brand.typography.body.family,
                    "weights": brand.typography.body.weights,
                    "google_url": brand.typography.body.google_url,
                },
            }
            if brand.typography
            else None
        ),
        "voice": (
            {
                "tone": brand.voice.tone,
                "do": brand.voice.do,
                "dont": brand.voice.dont,
                "examples": brand.voice.examples,
            }
            if brand.voice
            else None
        ),
        "persona_summary": persona.summary,
    }
    return json.dumps(payload, indent=2).encode("utf-8")


def _readme(brand: BrandAssets, persona: Persona) -> bytes:
    body = (
        f"{brand.brand_name}\n"
        f"{'-' * len(brand.brand_name)}\n\n"
        f"{brand.tagline}\n\n"
        "This kit was generated by Halo. Inside:\n\n"
        "  /logo/      Logo set — primary, mono dark, mono light, on-brand, avatar.\n"
        "  /mockups/   Product mockups — apply the brand to real objects.\n"
        "  /social/    Pre-sized social posts and stories.\n"
        "  /docs/      Brand guide PDF, pitch deck, manufacturing spec.\n"
        "  brand.json  Structured data dump (palette, type, voice).\n\n"
        "halo.app\n"
    )
    return body.encode("utf-8")


async def _gather_named(
    items: list[tuple[str, Awaitable[Optional[bytes]]]]
) -> list[tuple[str, Optional[bytes]]]:
    if not items:
        return []
    names = [name for name, _ in items]
    results = await asyncio.gather(*(coro for _, coro in items))
    return list(zip(names, results))


def _logo_items(brand: BrandAssets, client: httpx.AsyncClient) -> list[tuple[str, Awaitable[Optional[bytes]]]]:
    if not brand.logo:
        return []
    pairs = (
        ("primary.png", brand.logo.primary),
        ("mono_dark.png", brand.logo.mono_dark),
        ("mono_light.png", brand.logo.mono_light),
        ("on_brand.png", brand.logo.on_brand),
        ("avatar.png", brand.logo.avatar),
    )
    return [(name, _fetch(client, url)) for name, url in pairs if url]


def _mockup_items(
    brand: BrandAssets, client: httpx.AsyncClient
) -> list[tuple[str, Awaitable[Optional[bytes]]]]:
    return [
        (f"mockup_{_slug(m.label)}.png", _fetch(client, m.url))
        for m in brand.mockups
    ]


def _social_items(
    brand: BrandAssets, client: httpx.AsyncClient
) -> list[tuple[str, Awaitable[Optional[bytes]]]]:
    return [
        (f"{_slug(s.label)}.png", _fetch(client, s.url))
        for s in brand.social_kit
    ]


async def build_brand_kit_zip(
    brand: BrandAssets,
    persona: Persona,
    brand_guide_pdf_url: Optional[str],
    pitch_deck_pdf_url: Optional[str] = None,
    mfg_spec_pdf_url: Optional[str] = None,
    job_id: str = "",
) -> str:
    """Bundle every brand artifact into a ZIP and upload it.

    Failed fetches are skipped — the bundle remains coherent even if a
    single asset is unreachable. Returns the public URL of the ZIP.
    """
    async with httpx.AsyncClient() as client:
        logos = await _gather_named(_logo_items(brand, client))
        mockups = await _gather_named(_mockup_items(brand, client))
        social = await _gather_named(_social_items(brand, client))
        docs = await _gather_named([
            ("brand_guide.pdf", _fetch(client, brand_guide_pdf_url)),
            ("pitch_deck.pdf", _fetch(client, pitch_deck_pdf_url)),
            ("mfg_spec.pdf", _fetch(client, mfg_spec_pdf_url)),
        ])

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("brand.json", _brand_data_dump(brand, persona))
        zf.writestr("README.txt", _readme(brand, persona))
        for name, payload in logos:
            if payload is not None:
                zf.writestr(f"logo/{name}", payload)
        for name, payload in mockups:
            if payload is not None:
                zf.writestr(f"mockups/{name}", payload)
        for name, payload in social:
            if payload is not None:
                zf.writestr(f"social/{name}", payload)
        for name, payload in docs:
            if payload is not None:
                zf.writestr(f"docs/{name}", payload)

    return await storage.upload_image(
        buf.getvalue(),
        "brand-guides",
        f"jobs/{job_id}/{_slug(brand.brand_name)}_brand_kit.zip",
        content_type="application/zip",
    )
